Make bot usable from docker

diff --git a/ci b/ci
--- a/ci
+++ b/ci
@@ -1,14 +1,21 @@
 #!/usr/bin/env bash
 set -ex
 
+BASE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
+
+function die {
+  echo "$*" >&2
+  exit 1
+}
+
 case "$1" in
 
  jitpack)
    exec $0 mill -j 0 __.publishM2Local
  ;;
- 
+
  mill)
-   exec $0 cs launch mill -- "${@:2}"
+   exec $0 cs launch "mill:$(< .mill-version)" -- "${@:2}"
  ;;
 
  scalafmt)
@@ -16,22 +23,27 @@ case "$1" in
  ;;
 
  cs)
-   test -x cs || {
-     curl -o cs -qL https://git.io/coursier-cli
-     chmod +x cs
+   test -x $BASE_DIR/cs || {
+     curl -o $BASE_DIR/cs -qL https://git.io/coursier-cli
+     chmod +x $BASE_DIR/cs
    }
-   exec ./cs "${@:2}"
+   exec $BASE_DIR/cs "${@:2}"
  ;;
 
  example)
-   (cd example; ../ci mill example.runMain examplebot.ExampleBot)
+   test -f example/secrets.env || die "Missing example/secrets.env"
+   (
+     cd example
+     ../ci mill _.docker.build
+     docker run --rm --env-file secrets.env -ti keybase-scala-example
+   )
  ;;
 
  test)
-   $0 scalafmt --test
    $0 mill -j 0 __.compile
    (cd example; ../ci mill example.compile)
    # $0 mill -j 0 __.tests
+   $0 scalafmt --test
  ;;
 
  release)
